import {
  TProps,
  TPropsObj,
  TPropsHandle,
  TPropsInput,
  TPropsComment,
} from 'models/component.model';
import {
  TCheckboxInputProps,
  TCheckValidityRes,
  ICommentObj,
  TFileInputProps,
  TFormPageProps,
  TFormProps,
  TRadioInputProps,
  TSelectProps,
  TStateForm,
  TTextareaProps,
  TTextInputProps,
  FormValues,
  TDateInputProps,
  TValidateObj,
} from './form.model';
import { IGood } from './good.model';

export {
  TProps,
  TPropsObj,
  IGood,
  TPropsHandle,
  TPropsInput,
  TStateForm,
  ICommentObj,
  TCheckValidityRes,
  TPropsComment,
  TFormProps,
  TFormPageProps,
  TTextInputProps,
  TRadioInputProps,
  TSelectProps,
  TTextareaProps,
  TFileInputProps,
  TCheckboxInputProps,
  FormValues,
  TDateInputProps,
  TValidateObj,
};
